### ISSUE TITLE
heads up - this is public

### ISSUE THREAD

**Issue by gtallen1187** [boxuancui/sa-internal-site#1]
just wanted to let you know that anyone on github can see this.

**Comment by boxuancui** [comment]
There is no sensitive information here, and there is always BCG VPN to block all public traffic from internal access. I might want to reference some of the code in the future so I migrate it here. Do you think there is a problem? If yes I will take it offline.

**Comment by gtallen1187** [comment]
personally, i dont think its an issue, but just wanted to warn you in case someone else at BCG does.

**Comment by boxuancui** [comment]
I wonder who in BCG would ...
1. have a personal GitHub account,
2. and use it regularly,
3. so that he/she will come to my profile,
4. and browser through all my repos
5. to identify this repo and decides to continue reading,
6. and ultimately figures out that this is a site belongs to BCG internally.

If you think `count(distinct such_people) == 0`, would you mind closing this issue? :smiley:

**Comment by boxuancui** [comment]
sorry, forgot to mention `where such_people != "Greg Allen"`.

**Comment by gtallen1187** [comment]
``` javascript
percent(peopleFindingRepo.chance) <= 0.01 // true
```
